//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asientos()
        {
            this.AsientosXFuncion = new HashSet<AsientosXFuncion>();
        }
    
        public Nullable<int> fila { get; set; }
        public Nullable<int> columna { get; set; }
        public int codAsiento { get; set; }
        public string codZona { get; set; }
    
        public virtual ZonaEvento ZonaEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsientosXFuncion> AsientosXFuncion { get; set; }
    }
}
