//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public string codigo { get; set; }
        public string contenido { get; set; }
        public string fecha { get; set; }
        public int codEvento { get; set; }
        public string usuario { get; set; }
    
        public virtual Eventos Eventos { get; set; }
        public virtual CuentaUsuario CuentaUsuario { get; set; }
    }
}
