//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickNet.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class modelEntities : DbContext
    {
        public modelEntities()
            : base("name=modelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asientos> Asientos { get; set; }
        public virtual DbSet<AsientosXFuncion> AsientosXFuncion { get; set; }
        public virtual DbSet<Banco> Banco { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Comentarios> Comentarios { get; set; }
        public virtual DbSet<CuentaUsuario> CuentaUsuario { get; set; }
        public virtual DbSet<DetalleVenta> DetalleVenta { get; set; }
        public virtual DbSet<Eventos> Eventos { get; set; }
        public virtual DbSet<Funcion> Funcion { get; set; }
        public virtual DbSet<Locales> Locales { get; set; }
        public virtual DbSet<Organizador> Organizador { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<Perfiles> Perfiles { get; set; }
        public virtual DbSet<PeriodoVenta> PeriodoVenta { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Precio_Eventos> Precio_Eventos { get; set; }
        public virtual DbSet<Promociones> Promociones { get; set; }
        public virtual DbSet<PuntoVenta> PuntoVenta { get; set; }
        public virtual DbSet<Regalos> Regalos { get; set; }
        public virtual DbSet<RegaloxCliente> RegaloxCliente { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Tarjeta> Tarjeta { get; set; }
        public virtual DbSet<TipoCambio> TipoCambio { get; set; }
        public virtual DbSet<TipoTarjeta> TipoTarjeta { get; set; }
        public virtual DbSet<Turno> Turno { get; set; }
        public virtual DbSet<TurnoSistema> TurnoSistema { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
        public virtual DbSet<VentasXFuncion> VentasXFuncion { get; set; }
        public virtual DbSet<ZonaEvento> ZonaEvento { get; set; }
    }
}
