//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleVenta()
        {
            this.AsientosXFuncion = new HashSet<AsientosXFuncion>();
        }
    
        public string codPrecE { get; set; }
        public Nullable<int> cantEntradas { get; set; }
        public Nullable<double> Subtotal { get; set; }
        public Nullable<int> descTot { get; set; }
        public Nullable<double> total { get; set; }
        public int codDetalleVenta { get; set; }
        public int codVen { get; set; }
        public Nullable<int> entradasDev { get; set; }
        public string codFuncion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsientosXFuncion> AsientosXFuncion { get; set; }
        public virtual Precio_Eventos Precio_Eventos { get; set; }
        public virtual VentasXFuncion VentasXFuncion { get; set; }
    }
}
