//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eventos()
        {
            this.Comentarios = new HashSet<Comentarios>();
            this.Pago = new HashSet<Pago>();
            this.Funcion = new HashSet<Funcion>();
            this.PeriodoVenta = new HashSet<PeriodoVenta>();
        }
    
        public int codEvento { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<double> mAdeudado { get; set; }
        public Nullable<double> mTransferir { get; set; }
        public string lugar { get; set; }
        public Nullable<double> penCan { get; set; }
        public Nullable<double> penPost { get; set; }
        public Nullable<double> comision { get; set; }
        public Nullable<bool> esRecurrente { get; set; }
        public Nullable<int> destacado { get; set; }
        public Nullable<System.DateTime> fechDev { get; set; }
        public Nullable<bool> esImpri { get; set; }
        public Nullable<bool> esReser { get; set; }
        public Nullable<int> maxReserva { get; set; }
        public Nullable<System.DateTime> limReserva { get; set; }
        public int codOrg { get; set; }
        public string codPromotor { get; set; }
        public string idRegion { get; set; }
        public string idProvincia { get; set; }
        public bool necDoc { get; set; }
        public Nullable<int> codLocal { get; set; }
        public Nullable<int> idCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        public virtual Organizador Organizador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Funcion> Funcion { get; set; }
        public virtual Region Region { get; set; }
        public virtual Locales Locales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeriodoVenta> PeriodoVenta { get; set; }
        public virtual Region Region1 { get; set; }
    }
}
