//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio_Eventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Precio_Eventos()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public string codPrecioE { get; set; }
        public string precio { get; set; }
        public string codZona { get; set; }
        public string Etiqueta { get; set; }
        public string codPeriodo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual PeriodoVenta PeriodoVenta { get; set; }
        public virtual ZonaEvento ZonaEvento { get; set; }
    }
}
