//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegaloxCliente
    {
        public string FechaRecojo { get; set; }
        public int idRegalo { get; set; }
        public string usuario { get; set; }
    
        public virtual CuentaUsuario CuentaUsuario { get; set; }
        public virtual Regalos Regalos { get; set; }
    }
}
