//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCambio
    {
        public System.DateTime fechaCambio { get; set; }
        public Nullable<double> valor { get; set; }
        public string estado { get; set; }
    }
}
