//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        public string codPuntoVenta { get; set; }
        public int codTurnoSis { get; set; }
        public string estado { get; set; }
        public string usuario { get; set; }
    
        public virtual PuntoVenta PuntoVenta { get; set; }
        public virtual TurnoSistema TurnoSistema { get; set; }
    }
}
