//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TickNet.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasXFuncion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VentasXFuncion()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int codVen { get; set; }
        public string cantEntradas { get; set; }
        public Nullable<double> subtotal { get; set; }
        public Nullable<int> descuento { get; set; }
        public Nullable<double> total { get; set; }
        public string codFuncion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual Funcion Funcion { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
